version: '2.2'
services:
  chatgpt:
    image: test:1
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: eqAqC8vLDbBM
      MYSQL_DATABASE: chat-gpt
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 80:80
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --max-connections=1000 --slow_query_log=1 --slow_query_log_file=/var/lib/mysql/slow-log.log --long_query_time=1
    volumes:
      - ./data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
     MYSQL_ROOT_PASSWORD: eqAqC8vLDbBM
     MYSQL_DATABASE: chat-gpt
    ports:
      - 13306:3306
  redis:
    image: redis:6.2.12
    command: redis-server --requirepass hds2g23453kxsS1
    ports:
      - "6379:6379"